TipddyBackendBundle_dashboard:
    resource: "@TipddyBackendBundle/Resources/config/routing/dashboard.yml"
    prefix: /dashboard
    
TipddyBackendBundle_comment:
    resource: "@TipddyBackendBundle/Resources/config/routing/comment.yml"
    prefix: /comment

